name: Wordle GitHub Contributions

on:
  schedule:
    # at 08:00 on day-of-month 1
    - cron: "0 8 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contribution-grid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vchrombie/wordle-github-contributions@master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TITLE: ":octocat: GitHub Contributions Wordle"
          SHOW_MONTH: "True"
          OUTPUT_FILE: README.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Wordle contributions"
